# Generated by Django 5.0.6 on 2024-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengikut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_asli', models.CharField(max_length=255)),
                ('nama_samaran', models.CharField(max_length=50)),
            ],
        ),
    ]
